430TIL/test3/config/routes.rb
Rails.application.routes.draw do
  get '/login',to: 'session#new'
  post '/login',to: 'session#create'
  post '/logout',to: 'session#destroy'

  namespace :admin do
    resources :users
  end



  resources :tasks
  root to: "tasks#index"
  get 'test2/show'
  get 'test2/index'
  get 'test/show'
  get 'test/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

430TIL/test3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

430TIL/test3/app/models/task.rb
class Task < ApplicationRecord
  validates :name,presence: true,length:{maximum:30}
  validate :validate_name_not_include_commma

  belongs_to: user
  
  private

  def validate_name_not_include_commma
    errors.add(:name,"に,は含めることができません") if name&.include?('.')
  end
end

430TIL/test3/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name,presence:true
  validates :emai,presence: true,uniqueness: true

  has_many :tasks
end

430TIL/test3/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user),notice: "ユーザー#{@user.name}を追加しました"
    else
      render :new,status: 422
    end
  end

  def update
    @user = User.new(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user),notice: "ユーザー#{@user.name}を更新しました"
    else
      render :new,status: 422
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url,notice: "ユーザー#{@user.name}を削除しました"
  end


  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:admin,:password,:password_confirmation)
  end
end

430TIL/test3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url,notice: 'ログインしてください' unless current_user
  end

end

430TIL/test3/app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email:session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url,notice: 'ログインしました'
    else
      render :new,status: 422
    end

    def destroy
      reset_session
    end
  end

  private

  def session_params
    params.require(:session).permit(:email,:password)
  end
end

430TIL/test3/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to @task,notice: "タスク#{@task.name}が新規作成されました",status: 303
    else
      render :new,status: 422
    end
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_path,notice: "タスク:#{task.name}が編集されました" 
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy
    redirect_to tasks_path,notice: "タスク:#{task.name}を削除しました"
  end
  private 


  def task_params
    params.require(:task).permit(:name,:description)
  end
end

430TIL/test3/app/controllers/test2_controller.rb
class Test2Controller < ApplicationController
  def show
  end

  def index
  end
end

430TIL/test3/app/controllers/test_controller.rb
class TestController < ApplicationController
  def show
  end

  def index
  end
end

430TIL/test3/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

430TIL/test3/app/helpers/application_helper.rb
module ApplicationHelper
end

430TIL/test3/app/helpers/session_helper.rb
module SessionHelper
end

430TIL/test3/app/helpers/tasks_helper.rb
module TasksHelper
end

430TIL/test3/app/helpers/test2_helper.rb
module Test2Helper
end

430TIL/test3/app/helpers/test_helper.rb
module TestHelper
end

430TIL/test3/app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation 
    - user.errors.full_message.each do |message|
      li = message

= form_with model: [:admin,user],local:true do |f|
  .form-group 
  = f.label :name, '名前'
  = f.text_field :name ,class:'form-control'
  .form-group 
  = f.label :email, 'メールアドレス'
  = f.text_field :email ,class:'form-control'
  .form-group 
  = f.label :admin,class: 'form-check-label' do 
    = f.check_box  :admin,class: 'form-check-input'
    | 管理者権限
  .form-group 
  = f.label :password, 'パスワード'
  = f.password_field :password ,class:'form-control'
  .form-group 
  = f.label :password_confirmation, '確認用パスワード'
  = f.password_field :password_confirmation ,class:'form-control'

430TIL/test3/app/views/admin/users/edit.html.slim
h1 Admin::Users#edit
p Find me in app/views/admin/users/edit.html.slim



.nav.justify-content-end 
  = link_to '一覧',admin_users_path,class: 'nav-link'

= render partial: 'form',locals: {user:@user}

430TIL/test3/app/views/admin/users/index.html.slim
h1 Admin::Users#index
p Find me in app/views/admin/users/index.html.slim

table.table.table-hover 
  thead.thead-default 
    tr 
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
      th
  tbody 
    - @users.each do |user|
      tr 
        td = user.name
        td = user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td 
          =link_to '編集',edit_admin_user_path(user),class: 'btn btn-primary mr-3'
          =link_to '削除',[:admin,user], data: {turbo_method: :delete, turbo_confirm: '削除しやすか?'},class: 'btn btn-danger'

430TIL/test3/app/views/admin/users/new.html.slim
h1 Admin::Users#new
p Find me in app/views/admin/users/new.html.slim


.nav.justify-content-end 
  = link_to '一覧',admin_users_path,class: 'nav-link'

= render partial: 'form',locals: {user:@user}

430TIL/test3/app/views/admin/users/show.html.slim
h1 Admin::Users#show
p Find me in app/views/admin/users/show.html.slim


.nav.justify-content-end 
  = link_to '一覧',admin_user_path,class: 'nav-link'

table.table.table-hover 
  tbody 
    tr 
      th = User.human_attribute_name(:id)
      td = @user.id

    tr 
      th = User.human_attribute_name(:name)
      td = @user.name
    tr 
      th = User.human_attribute_name(:email)
      td = @user.email
    tr 
      th = User.human_attribute_name(:admin)
      td = @user.admin? 'あり' : 'なし'
    tr 
      th = User.human_attribute_name(:created_at)
      td= @user.created_at
    tr 
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集',edit_admin_user_path(@task),class: "btn btn-primary"
= link_to '削除',[:admin,@user], data: {turbo_method: :delete, turbo_confirm: '削除しやすか?'},class: "btn btn-danger"

430TIL/test3/app/views/tasks/_form.html.slim
.nav.justify-content-end
=link_to '一覧', tasks_path,class:'nav-link'

- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message


= form_with model: task,local:true do |f|
   .form-group
    = f.label :name
    = f.text_field :name ,class: 'form-control',id: :name
   .form-group
    = f.label :description
    = f.text_area :description,class: 'form-control',id: 'task-description'

    = f.submit '送信',class: 'btn btn-primary'

430TIL/test3/app/views/tasks/edit.html.slim
h1 Tasks#edit
p Find me in app/views/tasks/edit.html.slim

= render partial: "form",locals:{task:@task}

430TIL/test3/app/views/tasks/index.html.slim
h1 Tasks#index
p Find me in app/views/tasks/index.html.slim

=link_to '新規登録',new_task_path,class: "btn btn-primary"


.mb3 
table.table.table-hover
  thead.thead-default 
    tr 
      th = Task.human_attribute_name(:name)
      th = Task.human_attribute_name(:created_at)
      th
    tbody 
      - @tasks.each do |task|
        tr 
          td = link_to task.name,task_path(task)
          td = task.created_at
          td = link_to '編集',edit_task_path(task),class: "btn btn-primary"
          td = link_to '削除',task,  data: {turbo_method: :delete, turbo_confirm: '削除しやすか?'} ,class: "btn btn-danger"

430TIL/test3/app/views/tasks/new.html.slim
h1 Tasks#new
p Find me in app/views/tasks/new.html.slim



= render partial: "form",locals:{task:@task}

430TIL/test3/app/views/tasks/show.html.slim
h1 Tasks#show
p Find me in app/views/tasks/show.html.slim

.nav.justify-content-end 
  = link_to '一覧',tasks_path,class: 'nav-link'

table.table.table-hover 
  tbody 
    tr 
      th = Task.human_attribute_name(:id)
      td = @task.id

    tr 
      th = Task.human_attribute_name(:name)
      td = @task.name
    
    tr 
      th= Task.human_attribute_name(:description)
      td= simple_format(h(@task.description),{},sanitize:false,wrapper_tag: "div")
    tr 
      th = Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr 
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集',edit_task_path(@task),class: "btn btn-primary"
= link_to '削除',@task,method: :delete,data:{confirm:"タスク[#{@task.name}]を削除します。よろしいですか？"},class: "btn btn-danger"